baseURL = 'https://caoxuan5211.github.io/'
languageCode = 'en-us'
title = '怪话怪的博客'
theme = 'PaperMod'

# 添加搜索菜单
[menu]

  [[menu.main]]
    name = "搜索"
    url = "search/"
    weight = 10

# 添加主页背景失败喽
# [params.cover]
#   image = "/images/wanzi1.jpg"       # 也可以是外部链接
#   alt = "<~~图片丢了~~>"
#   relative = false               # 是否使用相对路径

# 搜索参数，参考 fuse.js 配置
[params]

  [params.assets]
    disableFingerprinting = true
  [params.fuseOpts]
    isCaseSensitive = false
    includeMatches = true
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]


[outputs]
  home = ["HTML", "RSS", "JSON"]
    

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true